# Generated by Django 3.0.7 on 2020-07-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='borrowedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
